# Generated by Django 5.2.5 on 2025-10-18 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_type', models.PositiveSmallIntegerField(choices=[(1, 'Wholesaler'), (2, 'Retailer'), (3, 'Agent'), (4, 'Brand'), (5, 'Online Store')], default=1)),
                ('source', models.PositiveSmallIntegerField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'Website'), (4, 'Exhibition'), (5, 'Referral'), (6, 'Other')], default=1)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'Contacted'), (3, 'Sample Sent'), (4, 'Negotiation'), (5, 'Closed Won'), (6, 'Closed Lost')], default=1)),
                ('interested_products', models.JSONField(blank=True, default=list)),
                ('target_price', models.CharField(blank=True, max_length=50, null=True)),
                ('order_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('company_size', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='lead_api_le_status_7d042b_idx'), models.Index(fields=['buyer_type'], name='lead_api_le_buyer_t_6b1dfc_idx'), models.Index(fields=['country'], name='lead_api_le_country_33d4b6_idx'), models.Index(fields=['source'], name='lead_api_le_source_cf8257_idx')],
            },
        ),
    ]
