# Generated by Django 5.2.5 on 2025-11-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('year_established', models.PositiveIntegerField(blank=True, null=True)),
                ('total_workers', models.PositiveIntegerField(blank=True, null=True)),
                ('total_factory_size', models.CharField(blank=True, help_text='e.g. 50,000 sq ft', max_length=100, null=True)),
                ('main_products', models.CharField(blank=True, help_text='Main items produced', max_length=255, null=True)),
                ('production_capacity_units', models.PositiveIntegerField(blank=True, help_text='Production capacity in units/month', null=True)),
                ('capacity_utilization', models.DecimalField(blank=True, decimal_places=2, help_text='Utilization in %', max_digits=5, null=True)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Average lead time in days', null=True)),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. TT, LC, etc.', max_length=100, null=True)),
                ('machinery_equipment', models.TextField(blank=True, help_text='List or details of key machines', null=True)),
                ('qc_inhouse_team', models.BooleanField(default=False)),
                ('qc_third_party', models.BooleanField(default=False)),
                ('qc_methods', models.JSONField(blank=True, default=list, help_text='QC types like Fabric Inspection, Metal Detection')),
                ('moq_units_per_style', models.PositiveIntegerField(blank=True, null=True)),
                ('moq_colors_per_style', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.ManyToManyField(blank=True, help_text='List of work capabilities.', related_name='suppliers', to='supplier_api.suppliercapabilitytype')),
                ('contact_persons', models.ManyToManyField(blank=True, related_name='suppliers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['-created_at'],
            },
        ),
    ]
