# Generated by Django 5.2.5 on 2025-11-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_api', '0002_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
