# Generated by Django 5.2.5 on 2025-11-07 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StyleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which statuses appear')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='style_api.stylestatus')),
            ],
            options={
                'verbose_name': 'Style Status',
                'verbose_name_plural': 'Style Statuses',
                'db_table': 'style_statuses',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['parent', 'order'], name='style_statu_parent__0a7769_idx'), models.Index(fields=['code', 'is_active'], name='style_statu_code_856ff2_idx')],
                'constraints': [models.UniqueConstraint(fields=('parent', 'name'), name='unique_status_name_per_parent')],
            },
        ),
    ]
