# Generated by Django 5.2.5 on 2025-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_api', '0002_season_created_at_season_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
