# Generated by Django 5.2.5 on 2025-11-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_api', '0005_alter_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
